[[dev_guide]]
= Developer Guide


CAUTION: You need Java 8 or newer in order to use BootHub.

BootHub is available in Maven Central and JCenter.

[subs="attributes",options="nowrap",title="Maven"]
----
&lt;dependency&gt;
    &lt;groupId&gt;{project-group}&lt;/groupId&gt;
    &lt;artifactId&gt;boothub-core&lt;/artifactId&gt;
    &lt;version&gt;{project-version}&lt;/version&gt;
&lt;/dependency&gt;
&lt;dependency&gt;
    &lt;groupId&gt;{project-group}&lt;/groupId&gt;
    &lt;artifactId&gt;boothub-db&lt;/artifactId&gt;
    &lt;version&gt;{project-version}&lt;/version&gt;
&lt;/dependency&gt;
&lt;dependency&gt;
    &lt;groupId&gt;{project-group}&lt;/groupId&gt;
    &lt;artifactId&gt;boothub-gradle-test&lt;/artifactId&gt;
    &lt;version&gt;{project-version}&lt;/version&gt;
&lt;/dependency&gt;
&lt;dependency&gt;
    &lt;groupId&gt;{project-group}&lt;/groupId&gt;
    &lt;artifactId&gt;boothub-heroku&lt;/artifactId&gt;
    &lt;version&gt;{project-version}&lt;/version&gt;
&lt;/dependency&gt;
&lt;dependency&gt;
    &lt;groupId&gt;{project-group}&lt;/groupId&gt;
    &lt;artifactId&gt;boothub-postgres&lt;/artifactId&gt;
    &lt;version&gt;{project-version}&lt;/version&gt;
&lt;/dependency&gt;
&lt;dependency&gt;
    &lt;groupId&gt;{project-group}&lt;/groupId&gt;
    &lt;artifactId&gt;boothub-web&lt;/artifactId&gt;
    &lt;version&gt;{project-version}&lt;/version&gt;
&lt;/dependency&gt;


----

[subs="attributes",options="nowrap",title="Gradle"]
----
compile '{project-group}:boothub-core:{project-version}'
compile '{project-group}:boothub-db:{project-version}'
compile '{project-group}:boothub-gradle-test:{project-version}'
compile '{project-group}:boothub-heroku:{project-version}'
compile '{project-group}:boothub-postgres:{project-version}'
compile '{project-group}:boothub-web:{project-version}'


----

*Command Line Build*

BootHub is built with http://www.gradle.org[Gradle] and requires JDK 8 or higher.
Clone the GitHub repository, `cd` into the top directory and start the build:

[source]
----
git clone https://github.com/boothub-org/boothub.git
cd boothub
./gradlew clean build            (On Windows: gradlew clean build)
----


*IntelliJ Idea*

- start the IntelliJ Idea IDE
- make sure that the Groovy plugin is enabled
- open _build.gradle_


*Eclipse*

- start the Eclipse IDE
- install the Groovy plugin; update site: http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/
- install a recent version of https://projects.eclipse.org/projects/tools.buildship[Buildship].
- import the project using the Gradle Project wizard



*Upload to Bintray*

The Bintray credentials must be available in a file called _gradle-local.properties_.
You can use link:{blob-root}/gradle-local.template.properties[gradle-local.template.properties] as template and adjust it accordingly.
